name: CI MAIN

on: [ push,workflow_dispatch ]

jobs:
  call-docker:
    uses: testVinaycicd/learn-1-terraform/.github/workflows/ci-main.yml@main   # must include  @refs
    with:
      tag: ${{ github.sha }}
      component_name: "shipping"
    secrets:
      DTKN: ${{ secrets.DTKN }}


